### PR TITLE
Group nbval command line options under 'nbval'.

### PR DESCRIPTION
**Pull request by ceball**
I _think_ this would just be a cosmetic change.

Example output of `pytest --help` (with e.g. coverage plugin also present)...

Before:
```
general:
  -k EXPRESSION         only run tests which match the given substring expression.
  -m MARKEXPR           only run tests matching given mark expression. example: -m
                        'mark1 and not mark2'.

[...]

  --nbval               Validate Jupyter notebooks
  --nbval-lax           Run Jupyter notebooks, only validating output on cells
                        marked with # NBVAL_CHECK_OUTPUT
  --sanitize-with=SANITIZE_WITH
                        File with regex expressions to sanitize the outputs. This
                        option only works when the --nbval flag is passed to py.test
  --current-env         Force test execution to use a python kernel in the same
                        environment that py.test was launched from. Without this
                        flag, the kernel stored in the notebook is used by default.
                        See also: --kernel-name
  --kernel-name=KERNEL_NAME
                        Force test execution to use the named kernel. If a kernel is
                        not named, the kernel stored in the notebook is used by
                        default. See also: --current-env
  --nbval-cell-timeout=NBVAL_CELL_TIMEOUT
                        Timeout for cell execution, in seconds.

[...]

coverage reporting with distributed testing support:
  --cov=[SOURCE]        Path or package name to measure during execution (multi-
                        allowed). Use --cov= to not do any source filtering and
                        record everything.
  --cov-report=TYPE     Type of report to generate: term, term-missing, annotate,
                        html, xml (multi-allowed). term, term-missing may be
                        followed by ":skip-covered". annotate, html and xml may be
                        followed by ":DEST" where DEST specifies the output
                        location. Use --cov-report= to not generate any output.
  --cov-config=PATH     Config file for coverage. Default: .coveragerc
  --no-cov-on-fail      Do not report coverage if test run fails. Default: False
  --no-cov              Disable coverage report completely (useful for debuggers).
                        Default: False
  --cov-fail-under=MIN  Fail if the total coverage is less than MIN.
  --cov-append          Do not delete coverage but append to current. Default: False
  --cov-branch          Enable branch coverage.
  --cov-context=CONTEXT
                        Dynamic contexts to use. "test" for now.
```

After:
```
general:
  -k EXPRESSION         only run tests which match the given substring expression.
  -m MARKEXPR           only run tests matching given mark expression. example: -m
                        'mark1 and not mark2'.

[...]

coverage reporting with distributed testing support:
  --cov=[SOURCE]        Path or package name to measure during execution (multi-allowed). Use --cov= to not do any source filtering and record everything.
  --cov-report=TYPE     Type of report to generate: term, term-missing, annotate, html, xml (multi-allowed). term, term-missing may be followed by ":skip-covered".
                        annotate, html and xml may be followed by ":DEST" where DEST specifies the output location. Use --cov-report= to not generate any output.
  --cov-config=PATH     Config file for coverage. Default: .coveragerc
  --no-cov-on-fail      Do not report coverage if test run fails. Default: False
  --no-cov              Disable coverage report completely (useful for debuggers). Default: False
  --cov-fail-under=MIN  Fail if the total coverage is less than MIN.
  --cov-append          Do not delete coverage but append to current. Default: False
  --cov-branch          Enable branch coverage.
  --cov-context=CONTEXT
                        Dynamic contexts to use. "test" for now.

Jupyter Notebook validation:
  --nbval               Run Jupyter notebooks, validating all output
  --nbval-lax           Run Jupyter notebooks, only validating output on cells marked with # NBVAL_CHECK_OUTPUT
  --sanitize-with=SANITIZE_WITH
                        File with regex expressions to sanitize the outputs. This option only works when the --nbval flag is passed to py.test
  --current-env         Force test execution to use a python kernel in the same enviornment that py.test was launched from.
  --nbval-cell-timeout=NBVAL_CELL_TIMEOUT
                        Timeout for cell execution, in seconds.
```

Note that grouping options is suggested in the pytest plugin cookiecutter:

https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/master/pytest-%7B%7Bcookiecutter.plugin_name%7D%7D/pytest_%7B%7Bcookiecutter.module_name%7D%7D.py#L7

### CODE REVIEW

**Comment by ceball** [comment]
Incidentally, should `--nbval` and `--nbval-lax` be mutually exclusive? I would argue that you should only be able to pass one, as it's probably an unintentional slip to pass both (i.e. did you definitely mean lax in that case?). But I see how it is reasonable to view `--lax` as a modifier of `--nbval` instead (which is how it currently works), so maybe it's fine.

**Comment by takluyver** [comment]
I think this is reasonable, assuming it doesn't break existing use cases.

It also seems reasonable to make `--nbval` and `--nbval-lax` mutually exclusive. I'd ultimately like to make 'lax' mode the default, because I think it's easier to start with just checking for errors, and build up output checks as an extra thing on top of that. But I've never got round to pushing for that change.

There's no real logic behind some of the options not having a prefix `nbval`. I think any new options we make should be prefixed, and maybe we should define prefixed aliases of the existing options.

**Comment by takluyver** [comment]
> So, I propose to add... `--nbval-sanitizer`... `--nbval-current-env`

Sounds good.

> Ideally I wouldn't want to affect existing users, though. 

Yeah, that's the hurdle that's stopped me tackling it. I was mentioning it more for context than asking you to tackle it in this PR, but as it happens I quite like your proposal for new names like `--nbval-run` and `--nbval-run-strict`. @vidartf, what do you think?

**Comment by vidartf** [comment]
New flags + old flags aliasing (ideally with a deprecation warning) sounds like a good solution 👍

**Comment by vidartf** [comment]
If I were to play devil's advocate, one argument against longer arguments name is that they end up being hard to remember/type, so you end up always putting the command behind a script / putting the args in setup.cfg, or alternatively always calling `pytest --help` every time you use nbval.

**Comment by ceball** [comment]
I agree that longer names are annoying.

Before going anywhere with any of this, I'll try to find answers to the following pytest questions:
  * Is there a way to tell pytest that options are mutually exclusive (like you [can for argparse](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_mutually_exclusive_group))?
  * Does grouping options have anything other than a cosmetic effect (it makes options appear grouped together via `--help` only)?
  * Is the pytest plugin convention really that every plugin should prefix every option?

> you end up always putting the command behind a script / putting the args in setup.cfg, or alternatively always calling pytest --help every time you use nbval

You could make a console script for nbval, so it can also be invoked without explicitly going via pytest ;) Then you could just type `nbval run` or `nbval run --strict`, etc. However, I think this isn't a good idea.

**Comment by ceball** [comment]
I haven't yet investigated pytest options, but I wanted to note I failed to appreciate that `--nbval-lax` is not just running the notebook - it also checks output for cells with `# NBVAL_CHECK_OUTPUT`. 

To me, it seems like there are three levels at which someone might want to use nbval:
1. Does the notebook execute all the way through without exception? (This is the thing I am most interested in. I set the bar low :) ).
2. Does the notebook fulfil 1, plus: do certain, specified outputs match?
3. Do _all_ outputs match (also fulfils 1 and 2)?

The below depends a bit on what I find out about pytest options, but I wanted to note down my thoughts anyway.

I don't like `--nbval-run` because it's long, and because `-run` is redundant (all options run the notebook - unless you foresee that ever changing?). 

Ideally I'd like something like `--nbval` with an `--output-check` option that defaults to `none`, e.g.
1. `pytest --nbval` (`--output-check` defaults to `none`; currently: not available)
2. `pytest --nbval --output-check=marked` (currently: `pytest --nbval-lax`)
3. `pytest --nbval --output-check=all` (currently: `pytest --nbval`)

Alternatively, instead of `--output-check`, it could be something less explicit like `--level` or `--strictness`. In any case, these suggestions all break backwards compatibility.

Trying to think up options to reflect these levels, while leaving the existing `--nbval` and `--nbval-lax` unaltered...

Deprecate `--nbval` but leave `--nbval-lax` as it is, and add two new options:
1. `pytest --nbval-run`
2. `pytest --nbval-lax`
3. `pytest --nbval-strict`

Or deprecate `--nbval` and `--nbval-lax`, and add one new option that takes values:
1. `pytest --nbval-run=unchecked`
2. `pytest --nbval-run=lax`
3. `pytest --nbval-run=strict`

Deprecate `--nbval` and `--nbval-lax`, and add a new option plus something to modify it:
1. `pytest --nbval-run` (`--output-check` defaults to none)
2. `pytest --nbval-run --output-check=marked`
3. `pytest --nbval-run --output-check=all`

**Comment by ceball** [comment]
@vidartf please consider this PR's contents and opening comment only, i.e. just a trivial/cosmetic change. I'll extract the rest of the discussion into one or more issues (with PR for any where it's already clear what to do).

**Review by vidartf — APPROVED** [review]

**Pull request merged**
