### PR TITLE
Fix coverage for coverage.py >=5

### LINKED ISSUE #129: Incompatible with coverage 5.0
It seems like `nbval` does not work with the just released coverage 5.0 package: https://travis-ci.org/qucontrol/krotov/jobs/625049383

### PR DESCRIPTION
**Pull request by vidartf**
Fixes #129

### CODE REVIEW

**Comment by vidartf** [comment]
The Python nightly build is causing the CI to fail. I thought that was marked as OK to fail?

**Comment by takluyver** [comment]
I'm fine with marking the Python nightly build OK to fail, or even dropping it entirely. I hope we'll get round to testing with beta versions of Python, but failures on alpha versions aren't that useful.

**Comment by takluyver** [comment]
Could you explain a bit how this works? Comparing `_cover4.py` to `_cover5.py`, there's a whole chunk of code in the former that's cut from the latter, and not replaced at all. You mention in #129 that it relies on the stability of pytest-cov - what exactly are we relying on that doing? (I can maybe guess roughly what this is, but it would be good to confirm that).

We should also record this detail in some comments, so we can remember if it breaks in the future.

Maybe we should ping the maintainers of pytest-cov to ask how safe it is to rely on the behaviour we do, and if there's any better way to play nicely with it.

**Comment by vidartf** [comment]
Better context for this change: I believe more recent versions of pytest-cov are more robust in how they merge files together, but I haven't actually checked this (it might be that the old code was needlessly complex). Either way, the new simpler code works well with modern versions of pytest-cov and coverage.py. For simplicity, I kept the old code as-is, in order to avoid having to do a matrix test for older versions of pytest-cov and coverage.py.

> You mention in #129 that it relies on the stability of pytest-cov

Yes, the coverage code relies on some of the internal details of how pytest-cov manages its coverage datafiles. It always has, and probably always will. This seems to have remained mostly stable (or strictly improved) since the code was originally added, so it is probably OK, but we risk it breaking again some time in the future.

> Maybe we should ping the maintainers of pytest-cov to ask how safe it is to rely on the behaviour we do, and if there's any better way to play nicely with it.

Sure.

**Comment by vidartf** [comment]
CI is now green after #135.

**Comment by takluyver** [comment]
Thanks Vidar!

**Pull request merged**
