### PR TITLE
Fix: passing `fspath` to `from_parent`

### PR DESCRIPTION
**Pull request by Borda**
fixing an error with probably latest ipython:
```
E   TypeError: from_parent() missing 1 required keyword-only argument: 'fspath'
```

### CODE REVIEW

**Comment by Borda** [comment]
@fangohr @takluyver @vidartf could you pls have look at the proposed hotfix? :rabbit:

**Comment by takluyver** [comment]
What version of pytest are you seeing this with? Is there a full traceback of the error? The current code looks like fspath is optional:

https://github.com/pytest-dev/pytest/blob/172c832cbdbfa407087ed6a895a298b48984da2a/src/_pytest/nodes.py

**Comment by Borda** [comment]
> he current code looks like `fspath` is optional

Yes but in the new version, it raises a different error

**Comment by takluyver** [comment]
I think I'm looking at the newest version of that code. Can I ask you to check what version you're running? `pytest --version`

**Comment by Borda** [comment]
> I think I'm looking at the newest version of that code. Can I ask you to check what version you're running? `pytest --version`

I had it in the log, but it seems that Azure keeps at most 2weeks' logs, and this is gone...
I may try to reproduce it but not sure when as I already had to switch to fork with this fix

**Pull request closed without merging**
