### PR TITLE
Drop Python 3.4 testing on TravisCI and enable 3.7 testing

### PR DESCRIPTION
**Pull request by rpep**

### CODE REVIEW

**Comment by takluyver** [comment]
There's an unfortunate problem on Travis meaning that we have to do a bit of extra work to test on 3.7 - see an example here for the changes needed:

https://github.com/European-XFEL/karabo_data/commit/e3de306152ffb3dfd38bd8290394e2d5dbcc312a

**Comment by takluyver** [comment]
The same issue also means that the 'nightly' builds are on an outdated 3.7 alpha version. It's fixable with a similar solution, but it might be easiest to just disable them. I'm never that convinced that allowed-failure builds are useful.

**Comment by rpep** [comment]
OK, will do :) thanks for the info!

**Comment by takluyver** [comment]
Now the 2.7 build on Appveyor is failing - we could replicate this workaround we already use on Travis to get an older version of doit:

https://github.com/computationalmodelling/nbval/commit/a321af98dfcc36f7dc9bebac625b81fce8c0b48a

Or we could decide it's time for nbval to drop Python 2.7 as well. @vidartf: any preference?

**Comment by vidartf** [comment]
Given how stable the code base is, I do not think we need to go in and clean up compatibility code quite yet (unless major work is planned?), but dropping CI/dev-tools support for 2.7 seems reasonable.

**Comment by takluyver** [comment]
Makes sense. I'm not planning any major work

**Comment by rpep** [comment]
I'd rather now drop 2.7 support just yet, as I think we're still using it in Fidimag. The Appveyor testing wasn't actually running 2.7 tests at all until now, and only testing against 3.5 - I turned it on in one of my commits.

**Comment by takluyver** [comment]
Fair enough. Then we'll need to copy the workaround from Travis for Appveyor.

**Comment by utensil** [comment]
> Or we could decide it's time for nbval to drop Python 2.7 as well. @vidartf: any preference?

[pygae/galgebra](https://github.com/pygae/galgebra/tree/15-print-pow) (a symbolic geometric algebra library) currently heavily relies on the fact that nbval supports Python 2.7, to verify it outputs exactly the same LaTeX formulas (or other outputs) under Python 3 as Python 2.7. This is also because galgebra has been port to Python only very recently thus the identical behavior under Python 2.7 and 3 is crucial to us.

Also we would like to thank you all for the great work on nbval.  ❤️ galgebra has plain text output, enhanced terminal output and LaTeX output for geometric algebra, without nbval, it would be tedious and error-prone to write tests for it, and most likely it would never reach a test coverage of [~66.55%](https://github.com/pygae/galgebra/pull/17#issuecomment-468536539).

I understand that we could always freeze the version of nval in our CI to ensure it still support Python 2.7, I'm just describing our use case and expressing our wish that the support for 2.7 would stay a little bit longer. 2019 is the end of life of Python 2.7 but it would not be an absolute end for legacy code. As an incrediblly helpful testing tool, it would be really nice for nbval to support Python 2.7 a little bit longer, and it could help the transition process from 2.7 to 3 (which some libraries are still working on it 😂 )

P.S. I noticed this issue because we are planning to test galgebra under more Python 3 versions in CI. We can apply the fix for CI under Python 3.7 as well. Thanks for the solution.

**Pull request merged**
