### PR TITLE
Use new Node.from_parent constructor when available

### PR DESCRIPTION
**Pull request by takluyver**
Fixes compatibility with pytest >=6.

Closes gh-139

### CODE REVIEW

**Comment by takluyver** [comment]
I'm the `hasattr` check from [pytest's docs](https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent), so we support older versions of pytest. I don't know if `from_parent` was available before the alternative was deprecated, but the deprecation was in 5.4, released March 2020.

**Comment by mattwthompson** [comment]
Just stopping by to say this fixes the issues I've run into with pytest 6+ today (now that it's released and pulled in by default in a lot of builds)

**Comment by vidartf** [comment]
I'll do a patch release.

**Comment by vidartf** [comment]
Released as 0.9.6

**Comment by takluyver** [comment]
Thanks Vidar :-)

**Comment by vidartf** [comment]
Thanks for the PR ;)

**Pull request merged**
