### PR TITLE
Fail output comparison on unexpected output

### LINKED ISSUE #81: Failing on a cell that returns no output normally
I have a notebook in which a code cell is used to run a shell command that, if all goes well, does not return anything. If the shell command breaks, an error message is returned and displayed as code cell output.

This error does not seem to result in a failed test.

To test this, I created a notebook with 3 code cells, `print('test')` in each, ran the notebook, cleared the output of the second code cell and then ran a test. It passed whereas I would have expected it to fail in the sense of cell 2 generating an output where there was none originally.

### PR DESCRIPTION
**Pull request by takluyver**
Closes #81.

### CODE REVIEW

**Comment by vidartf** [comment]
Regarding the failure in https://github.com/jupyter/notebook/pull/3212, I'm guessing the reason we didn't check for *added* outputs previously was because it didn't allow for keeping un-run notebooks for testing. Maybe a solution is to add a check for `execution_count` if output was added (unless the addition is an unexpected exception)?

**Comment by vidartf** [comment]
Or, formulated a little better: Cells without an `execution_count` should implicitly be evaluated in lax mode.

**Comment by takluyver** [comment]
That makes sense. Do you want to code it up?

**Comment by vidartf** [comment]
I'll submit a PR tomorrow.

**Comment by takluyver** [comment]
Thanks!

**Pull request merged**
