### PR TITLE
Fix missing coverage dependency

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@takluyver looks good like this, uploading a new revision on PyPI will be appreciated :-)

**Comment by takluyver** [comment]
Thanks! One other issue to fix, then I'll get a new release out.

**Comment by takluyver** [comment]
0.9 is out.

**Comment by serge-sans-paille** [comment]
On Tue, Jan 16, 2018 at 11:22:27AM +0000, Thomas Kluyver wrote:
> 0.9 is out.

Super great, thanks!

**Pull request merged**
