### PR TITLE
Set up sphinx documentation

### PR DESCRIPTION
**Pull request by vidartf**
Based on the previous documentation notebook (now ./docs/source/index.ipynb).

### CODE REVIEW

**Comment by vidartf** [comment]
PS: Do we want an RTD page?

**Comment by fangohr** [comment]
I'd say yes (RTD).

**Comment by takluyver** [comment]
@vidartf is that something you can set up yourself, or do you need me to create it?

**Comment by vidartf** [comment]
@takluyver I cannot import nbval in RTD, so it would have to be someone else (member of the org I think).

**Comment by takluyver** [comment]
Is your RTD username also vidartf ?

**Comment by takluyver** [comment]
I've created the project, but I think it needs @fangohr to set up the integration so it builds docs on every push.

**Comment by fangohr** [comment]
I have made @takluyver an admin - is that enough? Also, @vidartf - would you like more rights in this repo?? I couldn't see your username anywhere.

**Comment by takluyver** [comment]
Thanks Hans, I've set up the hook.

Vidar, if you let me know your username I'll add you to the RTD project.

**Comment by vidartf** [comment]
I'm `vidartf` most places, including RTD. Feel free to give me the rights there/here as you deem appropriate.

**Comment by takluyver** [comment]
I've invited you to collaborate on the project on Github, and added you on RTD.

Hans, I also added you to the RTD project.

**Pull request merged**
