### PR TITLE
make output_timeout configurable

### PR DESCRIPTION
**Pull request by renefritze**
I've followed the plugin option for `cell-timeout` with this and used the previously hardcoded value of `5` as the new default. This would close https://github.com/computationalmodelling/nbval/issues/136.

### CODE REVIEW

**Comment by vidartf** [comment]
For clarity, do you have some examples of when this could be useful? Are you e.g. generating outputs asynchronously?

**Comment by renefritze** [comment]
We've since moved on from using `nbval`, but I think the issue that was fixed for me with this commit was with pythreejs visualizations that wouldn't show otherwise. So my guess is yes, that was async related, but I'm not sure and can no longer check.

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
> We've since moved on from using `nbval`

so what are you using now?

>  I think the issue that was fixed

I see this argument in pytest help, but setting any walue does not have any effect https://github.com/computationalmodelling/nbval/issues/151#issuecomment-863022746

**Comment by Borda** [comment]
@fangohr @logicabrity @mvousden mind check this PR?

> For clarity, do you have some examples of when this could be useful? Are you e.g. generating outputs asynchronously?

I have the issue here, without any special reason...
https://dev.azure.com/PytorchLightning/Tutorials/_build/results?buildId=13607&view=logs&j=86bb8c30-297f-58f2-418d-1ad5be677653&t=16cfed9e-a41b-5b0e-892e-bf130fd21fce

**Comment by mvousden** [comment]
> [...] @mvousden mind check this PR?

I don't think I'm an appropriate developer to review this, as I haven't contributed to this repository, and I don't have understanding of the issue you're trying to fix. @fangohr may be able to recommend someone suitable though!

**Comment by renefritze** [comment]
> > We've since moved on from using `nbval`
> 
> so what are you using now?
> 

We don't ship notebooks that need to be hooked into pytest anymore. We've switched to markdown tutorials in sphinx with myst-nb.

**Comment by renefritze** [comment]
I'm cleaning up stale PRs, so I'll just leave this here in case there's interest in the future. [patch.txt](https://github.com/computationalmodelling/nbval/files/7755012/patch.txt)

**Pull request closed without merging**
