### PR TITLE
Feature/allow exceptions

### PR DESCRIPTION
**Pull request by wence-**
Allow notebook cells to raise exceptions, and do the appropriate checking that the traceback hasn't changed.

### CODE REVIEW

**Comment by takluyver** [comment]
I'm pretty sure we need some fuzzing of tracebacks for comparison, because Python tracebacks by default include full file paths for the code in each frame, which should be able to change without it being a test failure. This is made trickier because notebooks can be in many languages, each with their own traceback format. But maybe for now regex-ing the Python & IPython traceback formats is good enough.

I think 'allow exceptions' should be an option that you can add to specific cells, rather than setting for a notebook as a whole. We already have some code to look for special comments in specific cells, and @vidartf is working on enabling it with cell tags.

**Comment by wence-** [comment]
Yeah, I ducked the issue of paths in the traceback for the test by just raising in the notebook.  What I'd like is something equivalent to:

```python
with pytest.raises(SomeException):
    execute_cell()
```

But less intrusive to the code, since I'm distributing notebooks as teaching material, but want to ensure that they always run with our current codebase.

Perhaps a per-cell comment tag like so:

```python
# NBVAL_RAISES_EXCEPTION(RuntimeError)
raise RuntimeError(...)
```

and then check that the reply's `ename` matches the name specified in the magic comment.  But now I'm resigned to string-parsing to get the exception I want to test against, and so I'm leery of this.

**Comment by takluyver** [comment]
Maybe a simple compromise would be to add a comment like `# NBVAL_RAISES_EXCEPTION`, and then only check the ename, not the traceback, against the stored value in the notebook. That ensures that the same exception is raised, but avoids all the difficulties of parsing tracebacks and thinking about other languages. And it doesn't involve any extra info in magic comments (which I'm also leery of).

**Comment by wence-** [comment]
I'll have a go at that

**Comment by wence-** [comment]
Now done, please have a look.

**Comment by wence-** [comment]
(Removed commit that fixes the super call in kernel manager).

**Comment by takluyver** [comment]
Thanks! Can you also add a test of a failing test with a different exception name? You should be able to do it with a notebook in this folder:
https://github.com/computationalmodelling/nbval/tree/master/tests/ipynb-test-samples

The naming scheme is described in a docstring in this file: https://github.com/computationalmodelling/nbval/blob/master/tests/test_unit_tests_in_notebooks.py

**Comment by wence-** [comment]
Done, I updated the unit test file so that it actually runs the unit tests.  ca8df18a moved the unit test notebooks, but didn't update the test harness appropriately.

**Comment by takluyver** [comment]
Thanks! :-)

**Pull request merged**
